'use client'
import {FormEvent,useEffect,useState} from 'react'
import Modal from './Modal'
import {createClient} from '@/lib/supabase/client'

export default function GuideUploadForm({onClose,onSaved}:{onClose:()=>void,onSaved:()=>void}){
 const [cities,setCities]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{createClient().from('cities').select('id,name,slug').eq('active',true).order('name').then(({data})=>setCities(data||[]))},[])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const file=f.get('file') as File;const cityId=String(f.get('city_id'));const title=String(f.get('title')||'Guide touristique');const language=String(f.get('language')||'fr');if(!file||file.type!=='application/pdf'){setError('Sélectionnez un fichier PDF.');setBusy(false);return}const s=createClient();const {data:city}=await s.from('cities').select('slug').eq('id',cityId).single();const {data:last}=await s.from('guide_documents').select('version_number').eq('city_id',cityId).eq('language',language).order('version_number',{ascending:false}).limit(1).maybeSingle();const version=(last?.version_number||0)+1;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${city?.slug||cityId}/v${version}-${Date.now()}-${safe}`;const {error:up}=await s.storage.from('city-guides').upload(path,file,{contentType:'application/pdf',upsert:false});if(up){setError(up.message);setBusy(false);return}const {error:db}=await s.from('guide_documents').insert({city_id:cityId,language,title,storage_path:path,original_filename:file.name,version_number:version,status:'draft'});if(db){await s.storage.from('city-guides').remove([path]);setError(db.message);setBusy(false);return}onSaved();onClose()}
 return <Modal title="Importer un guide PDF" onClose={onClose}><form className="form" onSubmit={submit}><label>Ville*<select name="city_id" required><option value="">Sélectionner…</option>{cities.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Langue*<select name="language" required><option value="fr">Français (FR)</option><option value="en">English (EN)</option></select></label><label>Titre du guide*<input name="title" defaultValue="Guide touristique Croque ton Sud" required/></label><label>Fichier PDF*<input name="file" type="file" accept="application/pdf,.pdf" required/></label><p className="hint">Le fichier reste privé. Les voyageurs reçoivent un lien temporaire après un scan QR valide.</p>{error&&<p className="formerror">{error}</p>}<div className="formactions"><button type="button" onClick={onClose}>Annuler</button><button className="primary" disabled={busy}>{busy?'Import…':'Importer en brouillon'}</button></div></form></Modal>
}
