'use client'
import {useEffect,useMemo,useState} from 'react'
import {useParams} from 'next/navigation'
import {BookOpen,ChevronRight,Globe2,MapPin,ShieldX,UtensilsCrossed,Waves,Compass,Landmark,ShoppingBag,CalendarDays} from 'lucide-react'

type City={id:string;name:string;slug:string;cover_image_url?:string|null}
type Result={property:{label:string};cities:City[]}
const messages:Record<string,string>={invalid_qr:'Ce QR code est invalide.',qr_not_found:'Ce QR code est inconnu.',qr_blocked:'Ce guide est temporairement indisponible.',city_unavailable:'Cette destination est indisponible.',configuration_error:'Le guide est momentanément indisponible.'}
const categories=[['Restaurants',UtensilsCrossed],['Plages',Waves],['Activités',Compass],['Visites',Landmark],['Shopping',ShoppingBag],['Événements',CalendarDays]] as const
export default function TravelerGuide(){
 const {token}=useParams<{token:string}>(); const [data,setData]=useState<Result|null>(null),[selected,setSelected]=useState<City|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{if(!token)return;fetch('/api/traveler/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(messages[j.error]||'Guide indisponible.');setData(j);if(j.cities?.length===1)setSelected(j.cities[0])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token])
 const multi=(data?.cities?.length||0)>1; const heroStyle=useMemo(()=>selected?.cover_image_url?{backgroundImage:`linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.55)),url(${selected.cover_image_url})`}:undefined,[selected])
 if(loading)return <main className="travelerV4 travelerCenter"><img className="travelerLogo" src="/brand/logo-full.jpeg" alt="Croque ton Sud"/><div className="loader"/><p>Préparation de votre escapade…</p></main>
 if(error)return <main className="travelerV4 travelerCenter"><img className="travelerLogo" src="/brand/logo-full.jpeg" alt="Croque ton Sud"/><ShieldX size={44}/><h1>Guide indisponible</h1><p>{error}</p></main>
 if(multi&&!selected)return <main className="travelerV4"><header className="travelerHeader"><img className="travelerLogo" src="/brand/logo-full.jpeg" alt="Croque ton Sud"/><span>Votre mini-guide du Sud</span></header><section className="cityPicker"><div className="sunDot">☀</div><p className="script">Où souhaitez-vous croquer le Sud ?</p><h1>Choisissez votre destination</h1><p>Ce logement vous donne accès à plusieurs guides. Sélectionnez simplement la ville que vous souhaitez découvrir.</p><div className="cityChoices">{data?.cities.map(c=><button key={c.id} onClick={()=>setSelected(c)}><span className="cityThumb" style={c.cover_image_url?{backgroundImage:`url(${c.cover_image_url})`}:undefined}/><span><b>{c.name}</b><small>Découvrir le guide</small></span><ChevronRight/></button>)}</div></section><TravelerFooter/></main>
 return <main className="travelerV4"><header className="travelerHeader"><img className="travelerLogo" src="/brand/logo-full.jpeg" alt="Croque ton Sud"/>{multi&&<button className="changeCity" onClick={()=>setSelected(null)}>Changer de ville</button>}</header><section className="travelerHero" style={heroStyle}><div><MapPin size={18}/><span>Bienvenue à</span><h1>{selected?.name}</h1><p className="script">Les bonnes adresses sont par ici !</p></div></section><section className="travelerBody"><p className="intro">Restaurants, plages, activités et pépites locales : tout ce qu'il faut pour profiter pleinement de votre séjour.</p><div className="categoryGrid">{categories.map(([label,Icon])=><div key={label}><Icon/><span>{label}</span></div>)}<div className="moreCat"><span>Et bien plus…</span></div></div><div className="languageBox"><Globe2/><div><p className="script">Votre guide, votre langue</p><h2>Choisissez votre version</h2></div><a href={`/api/traveler/guide?city=${encodeURIComponent(selected?.id||'')}&lang=fr`}><span>🇫🇷</span><b>ACCÉDER AU GUIDE</b><small>Français</small><BookOpen/></a><a href={`/api/traveler/guide?city=${encodeURIComponent(selected?.id||'')}&lang=en`}><span>🇬🇧</span><b>OPEN THE GUIDE</b><small>English</small><BookOpen/></a></div></section><TravelerFooter/></main>
}
function TravelerFooter(){return <footer className="travelerFooter"><div/><p>Croque ton Sud · Profitez, découvrez, partagez.</p></footer>}
